AllCops:
  TargetRubyVersion: 3.0

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/FileName:
  Exclude:
    - "Gemfile"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - "lib/firebase/**/*"

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"
    - "lib/tasks/**/*"
